server:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/nft_market_place?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nft_market_place
    password: nft210613#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #  cache:
  #    type: redis
  #  redis:
  #    host: localhost
  #    port: 6379
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - file:${upload_path}

security:
  oauth2:
    client:
      access-token-validity-seconds: 2592000 #30일
      refresh-token-validity-seconds: 8640000 #100일
      client-id: nftApp
      client-secret: 1234
      scope:
        - app
      authorized-grant-types:
        - password
        - refresh_token
    authorization:
      check-token-access: "isAuthenticated()"
      jwt:
        key-value: mbr
        key-password: 1234
    resource:
      jwt:
        key-value: mbr
        key-password: 1234

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#로그 설정
logging.level:
  org.hibernate.SQL: debug

upload_path: /nft_marketplace/files/
upload_folder: upload

init_data: true