
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/jwt?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT%2b9
    driver-class-name: org.mariadb.jdbc.Driver
    username: jwt
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

my-app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass