spring:
  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:mariadb://localhost:3306/image_file?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT%2b9
    driver-class-name: org.mariadb.jdbc.Driver
    username: image_file
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

#File 리소스
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - file:${upload_path}

#File 저장 폴더
upload_path: /projectname/files/
upload_folder: upload