
spring:
  h2:
    console:
      enabled: true
    datasource:
      username: sa
      password:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      hikari:
        jdbc-url: jdbc:h2:mem:testdb
    #JPA 설정
    jpa:
      hibernate:
        ddl-auto: update
      properites:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect

my-app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass